### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by JoseRFJuniorLLMs** [ultrasaurus/ghostscript-cloud-function#2]
makePNG | Billing account not configured. External network is not accessible and quotas are severely limited. Configure billing account to remove these restriction

makePNG | Function execution took 3491 ms, finished with status: 'crash'

makePNG | Error: spawn lambda-ghostscript/bin/./gs ENOENT     at exports._errnoException    at Process.ChildProcess._handle.onexit (internal/child_process.js:197:32)     at onErrorNT (internal/child_process.js:376:16)     at _combinedTickCallback (internal/process/next_tick.js:80:11)     at process._tickDomainCallback (internal/process/next_tick.js:128:9)
 
![image](https://user-images.githubusercontent.com/488409/36089933-697b8824-0fc5-11e8-8e5a-090296ebf73d.png)

**Comment by prescottprue** [comment]
You need to upgrade your Firebase plan to Blaze to be able to make external network calls from functions.

The second error looks like you not having uploaded the lambda-ghostscript folder (which should be within your functions folder)
